import static com.stehno.photopile.repository.JdbcPhotoImageRepository.Sql.INSERT
import static com.stehno.photopile.repository.JdbcPhotoImageRepository.Sql.RETRIEVE

mappings {

    map(INSERT) {
        'insert into images(photo_id, version, scale, width, height, content_length, content_type) values (?, 1, ?, ?, ?, ?, ?)'
    }

    map(RETRIEVE) {
        'select photo_id, version, scale, width, height, content_length, content_type from images where photo_id=? and scale=?'
    }
}
