import static com.stehno.photopile.repository.JdbcPhotoRepository.Sql.*

mappings {

    // fragments

    // statements

    map(INSERT) {
        '''insert into photos (name,description,camera_make,camera_model,date_uploaded,date_taken,geo_longitude,geo_latitude,geo_altitude)
            values (?,?,?,?,?,?,?,?,?)
            returning id,version,date_updated
        '''
    }

    map(INSERT_TAGS) {
        'insert into photo_tags (photo_id,tag_id) values (?,?)'
    }

    map( SELECT ){
        '''select
            p.id,p.version,p.name,p.description,
            p.camera_make,p.camera_model,
            p.date_uploaded,p.date_updated,p.date_taken,
            p.geo_longitude,p.geo_latitude,p.geo_altitude,
            t.id as tag_id,t.version as tag_version,t.category as tag_category,t.name tag_name
           from photos p
                left outer join photo_tags pt on pt.photo_id=p.id
                left outer join tags t on t.id=pt.tag_id
        '''
    }

    map(RETRIEVE) {
        "${sql(SELECT)} where p.id=?"
    }
}