import static com.stehno.photopile.repository.JdbcTagRepository.Sql.*

mappings {

    map(INSERT) {
        'insert into tags (category,name) values (?,?) returning id,version'
    }

    map(DELETE) {
        'delete from tags where id=?'
    }

    map(COUNT_USES) {
        'select count(tag_id) from photo_tags where tag_id=?'
    }
}